-- Enderecos

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua das Flores', 123, 'Centro', 'Curitiba', 'PR', '01234-567');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida dos Girassóis', 456, 'Jardim Botânico', 'Balneário Camboriú', 'SC', '23456-789');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua das Acácias', 789, 'Jardim Primavera', 'Curitiba', 'PR', '34567-890');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua das Margaridas', 321, 'Vila Aurora', 'Curitiba', 'PR', '45678-901');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida das Palmeiras', 654, 'Jardim América', 'Curitiba', 'PR', '56789-012');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua dos Ipês', 987, 'Cidade Industrial', 'Curitiba', 'PR', '67890-123');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida das Hortênsias', 210, 'Centro', 'Curitiba', 'PR', '78901-234');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua das Orquídeas', 135, 'Jardim das Flores', 'Curitiba', 'PR', '89012-345');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida das Rosas', 246, 'Vila Bela', 'Curitiba', 'PR', '90123-456');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua dos Lírios', 579, 'Centro', 'Curitiba', 'PR', '01234-567');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida das Tulipas', 753, 'Jardim do Éden', 'Curitiba', 'PR', '23456-789');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua das Violetas', 842, 'Vila Nova', 'Curitiba', 'PR', '34567-890');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida das Begônias', 964, 'Centro', 'Curitiba', 'PR', '45678-901');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua das Margaridas', 123, 'Vila Aurora', 'Curitiba', 'PR', '01234-567');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida dos Cravos', 456, 'Centro', 'Curitiba', 'PR', '23456-789');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua das Dálias', 789, 'Jardim das Flores', 'Curitiba', 'PR', '34567-890');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida das Rosas', 321, 'Vila Bela', 'Curitiba', 'PR', '45678-901');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua das Orquídeas', 654, 'Jardim Botânico', 'Curitiba', 'PR', '56789-012');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida dos Lírios', 987, 'Centro', 'Curitiba', 'PR', '67890-123');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua dos Crisântemos', 210, 'Jardim Primavera', 'Curitiba', 'PR', '78901-234');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida das Margaridas', 135, 'Vila Nova', 'Curitiba', 'PR', '89012-345');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua das Bromélias', 246, 'Cidade Industrial', 'Curitiba', 'PR', '90123-456');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida das Violetas', 579, 'Centro', 'Curitiba', 'PR', '01234-567');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua dos Girassóis', 753, 'Jardim do Éden', 'Curitiba', 'PR', '23456-789');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida das Begônias', 842, 'Centro', 'Curitiba', 'PR', '34567-890');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua das Tulipas', 964, 'Vila Aurora', 'Curitiba', 'PR', '45678-901');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua das Azaleias', 111, 'Centro', 'Florianópolis', 'SC', '56789-012');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida dos Jasmins', 222, 'Jardim das Américas', 'Joinville', 'SC', '67890-123');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Rua dos Cravos', 333, 'Jardim Primavera', 'Blumenau', 'SC', '78901-234');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES('Avenida das Margaridas', 444, 'Vila Aurora', 'Florianópolis', 'SC', '89012-345');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua dos Jasmins', 111, 'Vila Bela Vista', 'Florianópolis', 'SC', '01234-567');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Azaleias', 222, 'Jardim das Américas', 'Joinville', 'SC', '23456-789');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua dos Crisântemos', 333, 'Centro', 'Florianópolis', 'SC', '34567-890');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Hortênsias', 444, 'Jardim Botânico', 'Joinville', 'SC', '45678-901');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Margaridas', 555, 'Vila das Flores', 'Florianópolis', 'SC', '56789-012');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida dos Lírios', 666, 'Jardim Primavera', 'Joinville', 'SC', '67890-123');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Orquídeas', 777, 'Centro', 'Belo Horizonte', 'MG', '78901-234');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Tulipas', 888, 'Vila Aurora', 'Joinville', 'SC', '89012-345');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Violetas', 999, 'Centro', 'Joinville', 'SC', '90123-456');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Begônias', 1010, 'Jardim do Éden', 'Joinville', 'SC', '01234-567');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Camélias', 111, 'Vila das Flores', 'Joinville', 'SC', '12345-678');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Margaridas', 222, 'Jardim Botânico', 'Belo Horizonte', 'MG', '23456-789');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua dos Cravos', 333, 'Centro', 'Belo Horizonte', 'MG', '34567-890');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Azaleias', 444, 'Vila Primavera', 'Florianópolis', 'SC', '45678-901');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Begônias', 555, 'Jardim América', 'Florianópolis', 'SC', '56789-012');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida dos Girassóis', 666, 'Vila das Flores', 'Belo Horizonte', 'MG', '67890-123');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Hortênsias', 777, 'Jardim Botânico', 'Belo Horizonte', 'MG', '78901-234');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Orquídeas', 888, 'Centro', 'Florianópolis', 'SC', '89012-345');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Tulipas', 999, 'Jardim América', 'Florianópolis', 'SC', '90123-456');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida dos Crisântemos', 1010, 'Vila Aurora', 'Belo Horizonte', 'MG', '01234-567');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Azaleias', 111, 'Jardim Botânico', 'Florianópolis', 'SC', '12345-678');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Violetas', 222, 'Vila Primavera', 'Belo Horizonte', 'MG', '23456-789');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua dos Girassóis', 333, 'Centro', 'Belo Horizonte', 'MG', '34567-890');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Margaridas', 444, 'Jardim América', 'Florianópolis', 'SC', '45678-901');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Orquídeas', 555, 'Vila das Flores', 'Belo Horizonte', 'MG', '56789-012');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida dos Cravos', 666, 'Jardim Botânico', 'Florianópolis', 'SC', '67890-123');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Hortênsias', 777, 'Centro', 'Belo Horizonte', 'MG', '78901-234');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Tulipas', 888, 'Vila Aurora', 'Florianópolis', 'SC', '89012-345');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua dos Lírios', 999, 'Jardim América', 'Florianópolis', 'SC', '90123-456');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Begônias', 1010, 'Vila Primavera', 'Belo Horizonte', 'MG', '01234-567');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Camélias', 123, 'Jardim Botânico', 'Florianópolis', 'SC', '12345-678');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida dos Cravos', 456, 'Centro', 'Joinville', 'SC', '23456-789');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Bromélias', 789, 'Jardim das Américas', 'Belo Horizonte', 'MG', '34567-890');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Azaleias', 321, 'Vila Primavera', 'Florianópolis', 'SC', '45678-901');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua dos Girassóis', 654, 'Centro', 'Joinville', 'SC', '56789-012');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Margaridas', 987, 'Jardim América', 'Belo Horizonte', 'MG', '67890-123');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Orquídeas', 210, 'Vila das Flores', 'Florianópolis', 'SC', '78901-234');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida dos Lírios', 543, 'Jardim Botânico', 'Joinville', 'SC', '89012-345');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Rua das Tulipas', 876, 'Centro', 'Belo Horizonte', 'MG', '90123-456');

INSERT INTO endereco (RUA, NUMERO, BAIRRO, CIDADE, ESTADO_UF, CEP)
VALUES ('Avenida das Violetas', 999, 'Vila Primavera', 'Florianópolis', 'SC', '01234-567');

-- TELEFONES - 50 TELEFONES

INSERT INTO telefone (TIPO_TELEFONE, DDD_TELEFONE, NUMERO_TELEFONE) VALUES
('Celular', '11', '912345678'),
('Celular', '21', '923456789'),
('Celular', '31', '934567890'),
('Celular', '41', '945678901'),
('Celular', '51', '956789012'),
('Celular', '12', '967890123'),
('Celular', '22', '978901234'),
('Celular', '32', '989012345'),
('Celular', '42', '900123456'),
('Celular', '52', '911234567'),
('Celular', '13', '922345678'),
('Celular', '23', '933456789'),
('Celular', '33', '944567890'),
('Celular', '43', '955678901'),
('Celular', '53', '966789012'),
('Celular', '14', '977890123'),
('Celular', '24', '988901234'),
('Celular', '34', '999012345'),
('Celular', '44', '900123456'),
('Celular', '54', '911234567'),
('Celular', '15', '922345678'),
('Celular', '25', '933456789'),
('Celular', '35', '944567890'),
('Celular', '45', '955678901'),
('Celular', '55', '966789012'),
('Celular', '16', '977890123'),
('Celular', '26', '988901234'),
('Celular', '36', '999012345'),
('Celular', '46', '900123456'),
('Celular', '56', '911234567'),
('Celular', '17', '922345678'),
('Celular', '27', '933456789'),
('Celular', '37', '944567890'),
('Celular', '47', '955678901'),
('Celular', '57', '966789012'),
('Celular', '18', '977890123'),
('Celular', '28', '988901234'),
('Celular', '38', '999012345'),
('Celular', '48', '900123456'),
('Celular', '58', '911234567'),
('Celular', '19', '922345678'),
('Celular', '29', '933456789'),
('Celular', '39', '944567890'),
('Celular', '49', '955678901'),
('Celular', '59', '966789012'),
('Celular', '20', '977890123'),
('Celular', '30', '988901234'),
('Celular', '40', '999012345'),
('Celular', '50', '900123456'),
('Celular', '60', '911234567');

-- IMAGEM

INSERT INTO imagem(NOME_IMAGEM, CAMINHO_IMAGEM) VALUES ('imagem_otavio', 'C:\Users\henri\Documents\Imagens_MYSQL\imagem_chefe\imagem_otavio')

-- FILIAL CURITIBA
INSERT INTO filial (NOME_FILIAL, CNPJ_FILIAL, EMAIL_FILIAL, ID_TELEFONE, ID_ENDERECO) 
VALUES ('Filial Curitiba', '12.345.678/0001-90' , 'filial_curitiba@example.com', 1, 1);

-- FILIAL BALNEÁRIO CAMBORIÚ
INSERT INTO filial (NOME_FILIAL, CNPJ_FILIAL, EMAIL_FILIAL, ID_TELEFONE, ID_ENDERECO) 
VALUES ('Filial Balneário Camboriú', '23.456.789/0001-01' ,'filial_balneario_camboriu@example.com', 2 , 2);

-- SETORES PRODUTOS - 7 SETORES PRODUTOS
INSERT INTO setor_produto (NOME_SETOR_PRODUTO) VALUES ('Açougue');
INSERT INTO setor_produto (NOME_SETOR_PRODUTO) VALUES ('Bebidas');
INSERT INTO setor_produto (NOME_SETOR_PRODUTO) VALUES ('Frios_Laticinios');
INSERT INTO setor_produto (NOME_SETOR_PRODUTO) VALUES ('Higiene_Perfumaria');
INSERT INTO setor_produto (NOME_SETOR_PRODUTO) VALUES ('Hortifruti');
INSERT INTO setor_produto (NOME_SETOR_PRODUTO) VALUES ('Mercearia');
INSERT INTO setor_produto (NOME_SETOR_PRODUTO) VALUES ('Padaraia');

-- SETORES FUNCIONÁRIOS - 5 SETORES FUNCIONÁRIOS
INSERT INTO setor_funcionario (NOME_SETOR_FUNCIONARIO) VALUES ('Marketing');
INSERT INTO setor_funcionario (NOME_SETOR_FUNCIONARIO) VALUES ('Financeiro');
INSERT INTO setor_funcionario (NOME_SETOR_FUNCIONARIO) VALUES ('RH');
INSERT INTO setor_funcionario (NOME_SETOR_FUNCIONARIO) VALUES ('Logística');
INSERT INTO setor_funcionario (NOME_SETOR_FUNCIONARIO) VALUES ('TI');

-- CHEFE SETOR
-- Chefe do setor de Marketing
INSERT INTO chefe (NOME_CHEFE, CPF_CHEFE, DATA_ADMISSAO, SALARIO_CHEFE, ID_FILIAL, ID_SETOR_FUNCIONARIO, ID_ENDERECO, ID_TELEFONE)  
VALUES ('Henrique Rocha', '12345678910' ,'2023-01-15', 11000.00, 1, 1, 3, 3);

-- Chefe do setor Financeiro 
INSERT INTO chefe (NOME_CHEFE, CPF_CHEFE, DATA_ADMISSAO, SALARIO_CHEFE, ID_FILIAL, ID_SETOR_FUNCIONARIO, ID_ENDERECO, ID_TELEFONE)  
VALUES ('Otavio Mello', '23456789021' ,'2022-08-20', 10100.00, 1, 2, 4, 4, 1);

-- Chefe do setor RH 
INSERT INTO chefe (NOME_CHEFE, CPF_CHEFE, DATA_ADMISSAO, SALARIO_CHEFE, ID_FILIAL, ID_SETOR_FUNCIONARIO, ID_ENDERECO, ID_TELEFONE)  
VALUES ('Albert Einstein', '34567890132' ,'2022-11-10', 10030.00, 1, 3, 5, 5);

-- Chefe do setor Logística 
INSERT INTO chefe (NOME_CHEFE, CPF_CHEFE, DATA_ADMISSAO, SALARIO_CHEFE, ID_FILIAL, ID_SETOR_FUNCIONARIO, ID_ENDERECO, ID_TELEFONE)  
VALUES ('Gustavo Lima', '45678901243' ,'2023-03-05', 10080.00, 1, 4, 6, 6);

-- Chefe do setor TI 
INSERT INTO chefe (NOME_CHEFE, CPF_CHEFE, DATA_ADMISSAO, SALARIO_CHEFE, ID_FILIAL, ID_SETOR_FUNCIONARIO, ID_ENDERECO, ID_TELEFONE)  
VALUES ('Marcos Aurelio', '56789012354' ,'2022-10-01', 12392.00, 1, 5, 7, 7);

-- CLIENTE 3
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Anderson Santos', '89012345687', 'anderson@example.com', '1980-12-05', 'M', 1, 9, 9);

-- CLIENTE 4
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Fernanda Costa', '90123456798', 'fernanda@example.com', '1993-06-23', 'F', 1, 10, 10);

-- CLIENTE 5
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Rodrigo Oliveira', '01234567809', 'rodrigo@example.com', '1987-11-15', 'M', 1, 11, 11);

-- CLIENTE 6
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Luciana Pereira', '12345678910', 'luciana@example.com', '1984-08-07', 'F', 1, 12, 12);

-- CLIENTE 7
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Gustavo Silva', '23456789021', 'gustavo@example.com', '1996-03-12', 'M', 1, 13, 13);

-- CLIENTE 8
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Carla Mendonça', '34567890132', 'carla@example.com', '1990-09-28', 'F', 1, 14, 15);

-- CLIENTE 9
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Paulo Rocha', '45678901243', 'paulo@example.com', '1989-12-03', 'M', 1, 15, 15);

-- CLIENTE 10
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Sandra Alves', '56789012354', 'sandra@example.com', '1994-05-20', 'F', 1, 16, 16);

-- CLIENTE 11
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Marcelo Santos', '67890123465', 'marcelo@example.com', '1982-02-17', 'M', 1, 17, 17);

-- CLIENTE 12
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Cristina Lima', '78901234576', 'cristina@example.com', '1997-08-25', 'F', 1, 18, 18);

-- CLIENTE 13
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Ricardo Oliveira', '8012345687', 'ricardo@example.com', '1985-10-10', 'M', 2, 19, 19);

-- CLIENTE 14
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Lúcia Costa', '9012345679', 'lucia@example.com', '1998-04-05', 'F', 2, 20, 20);

-- CLIENTE 15
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Mário Oliveira', '0123467809', 'mario@example.com', '1986-07-15', 'M', 2, 21, 21);

-- CLIENTE 16
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Ricardo Pereira', '1234567910', 'ricardopereira@example.com', '1980-02-05', 'M', 2, 22, 22);

-- CLIENTE 17
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Carolina Silva', '2345789021', 'carolina@example.com', '1993-05-23', 'F', 2, 23, 23);

-- CLIENTE 18
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Rodrigo Mendes', '3456789013', 'rodrigomendes@example.com', '1987-08-15', 'M', 2, 24, 24);

-- CLIENTE 19
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Luíza Costa', '5678901243', 'luiza@example.com', '1984-11-07', 'F', 2, 25, 25);

-- CLIENTE 20
INSERT INTO cliente (NOME_CLIENTE, CPF_CLIENTE, EMAIL, DATA_NASCIMENTO, SEXO, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Felipe Souza', '5679012354', 'felipe@example.com', '1997-06-25', 'M', 2, 26, 26);





-- FUNCIONÁRIO 2
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Ana Santos', '78901234576', '2020-08-20', 3500.00, '09:00:00', 'Analista Financeiro', 'F', '18:00:00', 2, 2, 1, 27, 27);

-- FUNCIONÁRIO 3
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('José Lima', '89012345687', '2022-01-15', 2800.00, '08:30:00', 'Assistente de RH', 'M', '17:30:00', 3, 3, 1, 28, 28);

-- FUNCIONÁRIO 4
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Aline Pereira', '90123456798', '2021-03-05', 3200.00, '08:00:00', 'Assistente de Logística', 'F', '17:30:00', 4, 4, 1, 29, 29);

-- FUNCIONÁRIO 5
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Felipe Oliveira', '01234567809', '2020-11-10', 4000.00, '08:00:00', 'Analista de TI', 'M', '17:00:00', 5, 5, 1, 30, 30);

-- FUNCIONÁRIO 6
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Mariana Costa', '12345678910', '2021-07-05', 3200.00, '09:00:00', 'Vendedora', 'F', '18:00:00', 1, 1, 1, 31, 31);

-- FUNCIONÁRIO 7
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Lucas Almeida', '23456789021', '2022-03-20', 3000.00, '08:30:00', 'Assistente Financeiro', 'M', '17:30:00', 2, 2, 1, 32, 32);

-- FUNCIONÁRIO 8
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Carla Santos', '34567890132', '2021-12-10', 3500.00, '08:00:00', 'Analista de RH', 'F', '17:30:00', 3, 3, 1, 33, 34);

-- FUNCIONÁRIO 9
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Marcos Lima', '45678901243', '2020-10-01', 3800.00, '08:00:00', 'Analista de Logística', 'M', '17:00:00', 4, 4, 1, 35, 35);

-- FUNCIONÁRIO 10
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Cristina Mendes', '56789012354', '2021-06-23', 3200.00, '09:00:00', 'Analista de TI', 'F', '18:00:00', 5, 5, 1, 36, 36);

-- FUNCIONÁRIO 11
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Pedro Silva', '67890123465', '2021-09-18', 3000.00, '08:00:00', 'Vendedor', 'M', '17:00:00', 1, 1, 1, 37, 37);

-- FUNCIONÁRIO 12
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Fernanda Alves', '7890123476', '2020-07-15', 3500.00, '09:00:00', 'Analista Financeiro', 'F', '18:00:00', 2, 2, 1, 38, 38);

-- FUNCIONÁRIO 13
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Ricardo Oliveira', '8901234587', '2022-05-05', 3200.00, '08:30:00', 'Assistente de RH', 'M', '17:30:00', 3, 3, 1, 39, 39);

-- FUNCIONÁRIO 14
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Amanda Costa', '9012456798', '2021-11-20', 3000.00, '08:00:00', 'Assistente de Logística', 'F', '17:30:00', 4, 4, 2, 40, 40);

-- FUNCIONÁRIO 15
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Gustavo Martins', '0123456789', '2021-02-28', 3500.00, '08:00:00', 'Analista de TI', 'M', '17:00:00', 5, 5, 2, 41, 41);

-- FUNCIONÁRIO 16
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Juliana Santos', '2346789021', '2022-07-10', 2800.00, '09:00:00', 'Vendedora', 'F', '18:00:00', 1, 1, 2, 42, 42);

-- FUNCIONÁRIO 17
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Bruno Almeida', '3467890132', '2021-04-15', 3200.00, '08:30:00', 'Assistente Financeiro', 'M', '17:30:00', 2, 2, 2, 43, 43);

-- FUNCIONÁRIO 18
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Larissa Pereira', '4567801243', '2022-10-20', 3000.00, '08:00:00', 'Analista de RH', 'F', '17:30:00', 3, 3, 2, 44, 44);

-- FUNCIONÁRIO 19
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Diego Lima', '5678901235', '2021-09-05', 3800.00, '08:00:00', 'Coordenador de Logística', 'M', '17:00:00', 4, 4, 2, 45, 45);

-- FUNCIONÁRIO 20
INSERT INTO funcionario (NOME_FUNCIONARIO, CPF_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, SALARIO_FUNCIONARIO, HORARIO_ENTRADA, CARGO, SEXO, HORARIO_SAIDA, ID_SETOR_FUNCIONARIO, ID_CHEFE, ID_FILIAL, ID_ENDERECO, ID_TELEFONE)
VALUES ('Camila Oliveira', '67890123465', '2022-06-15', 3200.00, '09:00:00', 'Analista de TI', 'F', '18:00:00', 5, 5, 2, 46, 46);


-- Produto

-- Açougue

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Alcatra Moida', 'Carne Premium Moida', 23.90, 'Friboi', 'kg', 50, 1);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Peito Frango', 'Peito de Frango Cru', 11.99, 'Festmax', 'kg', 50, 1);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Sobrecoxa de Frango', 'Sobrecoxa de Frango', 11.99, 'Sadia', 'UN', 50, 1);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Tiras de Coxão Mole', 'Pedaços de Coxão Mole', 23.90, 'Festmax', 'kg', 50, 1);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Bife Ancho', 'Carne Premium', 30.00, 'Maturatta', 'kg', 50, 1);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Picanha', 'Carne Premium', 55.99, 'Festmax', 'kg', 50, 1);


-- Bebidas

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Cerveja', 'Bebida alcoolica de cevada', 6.49, 'Heineken', 'UN', 50, 2);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Coca Cola', 'Refrigerante de Cola', 5.99, 'CocaCola', 'UN', 50, 2);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Vinho tinto', 'Vinho de uva', 29.90, ' Terenzi Bramaluce', 'UN', 50, 2);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Guaraná Antártica', 'Refrigerante Sabor Guaraná', 3.99, 'GuaranaAntartica', 'UN', 50, 2);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Pepsi', 'Refrigerante de Cola', 3.69, 'Pepsi', 'UN', 50, 2);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Energético Red Bull', 'Energético', 8.00, 'RedBull', 'UN', 50, 2);


-- Frios e Laticinios

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Queijo Mussarela', 'Queijo Mussarela', 10.99, 'Tirol', 'UN', 50, 3);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Presunto', 'Presunto Defumado', 8.89, 'Sadia', 'UN', 50, 3);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Manteiga', 'Manteiga', 9.00, 'Qualy', 'UN', 50, 3);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Iogurte', 'Ioguerte sabor morango', 15.00, 'Danone', 'UN', 50, 3);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Leite', 'Leite', 5.19, 'Lider', 'UN', 50, 3);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Requeijão', 'Requeijão', 9.90, 'Nestle', 'UN', 50, 3);


-- Higiene e Perfumaria

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Sabone lquido', 'Sabonete Liquido', 12.00, "Johnsons's", 'UN', 50, 4);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Shampoo', 'Shampoo para cabelos', 22.99, 'Dove', 'UN', 50, 4);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Desodorante', 'Desodorante Masculino', 20.00, 'Nivea', 'UN', 50, 4);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Detergente Líquido', 'Detergente Liquido Neutro', 7.00, 'Ype', 'UN', 50, 4);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Amaciante de roupas', 'Amaciante de Lavanda', 25.00, 'Comfort', 'UN', 50, 4);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Sabão em pó', 'Sabão em pó', 20.99, 'Festmax', 'kg', 50, 4);


-- Hortifruti

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Maçã', 'Maçã Gala', 4.50, 'Festmax', 'kg', 50, 5);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Bananas', 'Banana Prata', 3.20, 'Festmax', 'kg', 50, 5);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Tomate', 'Tomate', 5.00, 'Festmax', 'kg', 50, 5);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Cenoura', 'Cenoura', 2.80, 'Festmax', 'kg', 50, 5);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Alface', 'Alface', 2.00, 'Festmax', 'UN', 50, 5);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Morango', 'Morango', 8.90, 'Festmax', 'kg', 50, 5);


-- Mercearia

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Arroz', 'Arroz Branco', 4.79, 'Camil', 'UN', 50, 6);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Feijão', 'Feijão Preto', 7.50, 'Camil', 'UN', 50, 6);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Macarrão', 'Macarrão Penne', 9.99, 'Galo', 'UN', 50, 6);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Óleo de Soja', 'Oléo de Soja', 7.00, 'Liza', 'UN', 50, 6);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Farinha de Trigo', 'Farinha de Trigo', 6.00, 'Venturelli', 'UN', 50, 6);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Acúcar refinado', 'Açucar refinado0', 11.99, 'Uniao', 'UN', 50, 6);


-- Padaria 

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Pão Francês', 'Pão Francês', 10.99, 'Festmax', 'kg', 50, 7);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Pão de Forma', 'Pão de Forma', 5.30, 'Visconti', 'UN', 50, 7);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Pão de Queijo', 'Pão de Queijo', 6.00, 'Festmax', 'kg', 50, 7);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Croissant', 'Croissant', 8.00, 'Festmax', 'UN', 50, 7);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Coxinha', 'Coxinha de Frango', 6.50, 'Festmax', 'UN', 50, 7);

INSERT INTO produto (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO, MARCA, UNIDADE_MEDIDA, QUANTIDADE_ESTOQUE, ID_SETOR_PRODUTO)
VALUES ('Sonho', 'Sonho', 1.80, 'Festmax', 'UN', 50, 7);