CREATE DATABASE festmax;

USE festmax;


CREATE TABLE endereco(
    ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(255) NOT NULL,
    NUMERO INT NOT NULL,
    BAIRRO VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    ESTADO_UF CHAR(2) NOT NULL,
    CEP VARCHAR(9) NOT NULL
);

CREATE TABLE telefone(
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_TELEFONE VARCHAR(50) NOT NULL,
    DDD_TELEFONE CHAR(2) NOT NULL,
    NUMERO_TELEFONE CHAR(9) NOT NULL
);

CREATE TABLE imagem(
    ID_IMAGEM INT PRIMARY KEY AUTO_INCREMENT,
    NOME_IMAGEM VARCHAR(255) NOT NULL,
    CAMINHO_IMAGEM VARCHAR(255) NOT NULL

);

CREATE TABLE filial (
    ID_FILIAL INT PRIMARY KEY AUTO_INCREMENT,
    NOME_FILIAL VARCHAR(255) NOT NULL,
    CNPJ_FILIAL VARCHAR(18) NOT NULL,
    EMAIL_FILIAL VARCHAR(255) NOT NULL,
    ID_ENDERECO INT, 
    ID_TELEFONE INT,
    FOREIGN KEY(ID_ENDERECO) REFERENCES endereco(ID_ENDERECO),
    FOREIGN KEY(ID_TELEFONE) REFERENCES telefone(ID_TELEFONE)
);

CREATE TABLE setor_funcionario (
    ID_SETOR_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_SETOR_FUNCIONARIO VARCHAR(255)
);

CREATE TABLE setor_produto (
    ID_SETOR_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_SETOR_PRODUTO VARCHAR(255)
);

CREATE TABLE chefe (
    ID_CHEFE INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CHEFE VARCHAR(255) NOT NULL,
    CPF_CHEFE CHAR(14) NOT NULL UNIQUE,
    DATA_ADMISSAO DATE NOT NULL,
    SALARIO_CHEFE DECIMAL(10,2) NOT NULL,
    ID_FILIAL INT,
    ID_SETOR_FUNCIONARIO INT,
    ID_ENDERECO INT,
    ID_TELEFONE INT,
    ID_IMAGEM INT,
    FOREIGN KEY (ID_FILIAL) REFERENCES filial (ID_FILIAL),
    FOREIGN KEY (ID_SETOR_FUNCIONARIO) REFERENCES setor_funcionario (ID_SETOR_FUNCIONARIO),
    FOREIGN KEY (ID_ENDERECO) REFERENCES endereco (ID_ENDERECO),
    FOREIGN KEY (ID_TELEFONE) REFERENCES telefone (ID_TELEFONE),
    FOREIGN KEY (ID_IMAGEM) REFERENCES imagem(ID_IMAGEM)
);

CREATE TABLE cliente (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CLIENTE VARCHAR(255) NOT NULL,
    CPF_CLIENTE CHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    SEXO ENUM("M", "F"),
    ID_FILIAL INT,
    ID_ENDERECO INT,
    ID_TELEFONE INT,
    ID_IMAGEM INT,
    FOREIGN KEY (ID_FILIAL) REFERENCES filial (ID_FILIAL),
    FOREIGN KEY (ID_ENDERECO) REFERENCES endereco (ID_ENDERECO),
    FOREIGN KEY (ID_TELEFONE) REFERENCES telefone (ID_TELEFONE),
    FOREIGN KEY (ID_IMAGEM) REFERENCES imagem(ID_IMAGEM)
);

CREATE TABLE funcionario (
    ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_FUNCIONARIO VARCHAR(255) NOT NULL,
    CPF_FUNCIONARIO CHAR(14) NOT NULL UNIQUE,
    DATA_ADMISSAO_FUNCIONARIO DATE NOT NULL,
    SALARIO_FUNCIONARIO DECIMAL(10,2) NOT NULL,
    HORARIO_ENTRADA TIME NOT NULL,
    CARGO VARCHAR(255),
    SEXO ENUM("M", "F"),
    HORARIO_SAIDA TIME NOT NULL,
    ID_SETOR_FUNCIONARIO INT,
    ID_CHEFE INT,
    ID_FILIAL INT,
    ID_ENDERECO INT,
    ID_TELEFONE INT,
    FOREIGN KEY (ID_SETOR_FUNCIONARIO) REFERENCES setor_funcionario (ID_SETOR_FUNCIONARIO),
    FOREIGN KEY (ID_CHEFE) REFERENCES chefe (ID_CHEFE),
    FOREIGN KEY (ID_FILIAL) REFERENCES filial (ID_FILIAL),
    FOREIGN KEY (ID_ENDERECO) REFERENCES endereco (ID_ENDERECO),
    FOREIGN KEY (ID_TELEFONE) REFERENCES telefone (ID_TELEFONE)
);

CREATE TABLE produto (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(255) NOT NULL,
    DESCRICAO_PRODUTO TEXT,
    PRECO_PRODUTO DECIMAL(10,2) NOT NULL,
    MARCA VARCHAR(255) NOT NULL,
    UNIDADE_MEDIDA ENUM('KG', 'L', 'UN'),
    QUANTIDADE_ESTOQUE INT NOT NULL,
    ID_SETOR_PRODUTO INT,
    ID_IMAGEM INT,
    FOREIGN KEY (ID_SETOR_PRODUTO) REFERENCES setor_produto (ID_SETOR_PRODUTO),
    FOREIGN KEY (ID_IMAGEM) REFERENCES imagem(ID_IMAGEM)
);

CREATE TABLE compra (
    ID_COMPRA INT PRIMARY KEY AUTO_INCREMENT,
    DATA_COMPRA DATE NOT NULL,
    TOTAL_PAGO DECIMAL(10,2) NOT NULL,
    FORMA_PAGAMENTO ENUM("CRÉDITO", "DÉBITO", "PIX"),
    ID_CLIENTE INT,
    ID_FUNCIONARIO INT,
    ID_FILIAL INT,
    FOREIGN KEY(ID_CLIENTE) REFERENCES cliente (ID_CLIENTE),
    FOREIGN KEY(ID_FUNCIONARIO) REFERENCES funcionario (ID_FUNCIONARIO),
    FOREIGN KEY (ID_FILIAL) REFERENCES filial (ID_FILIAL)
);


CREATE TABLE item_comprado (
    ID_ITEM_COMPRADO INT AUTO_INCREMENT PRIMARY KEY,
    QUANTIDADE INT,
    PRECO_PRODUTO DECIMAL(10,2) NOT NULL,
    ID_COMPRA INT,
    ID_PRODUTO INT,
    FOREIGN KEY (ID_COMPRA) REFERENCES compra (ID_COMPRA),
    FOREIGN KEY (ID_PRODUTO) REFERENCES produto (ID_PRODUTO)
);
